- hosts: localhost 
  vars_files:
    - vars/alteon_params.yml
  tasks:
    - name: active alteon interface 1 config
      radware.radware_modules.alteon_config_l3_interface:
        provider: "{{ radware_provider[0] }}"
        state: "{{ state }}"
        parameters:
          index: 1
          state: enabled
          ip4_address: "{{ ha.peer_interface_va_1 }}"
          peer_ip: "{{ ha.peer_interface_va_2 }}"
          ip4_subnet: 255.255.255.0
          ip_ver: ipv4
          vlan: 1
          
    # - name: active alteon interface 2 config
    #   radware.radware_modules.alteon_config_l3_interface:
    #     provider: "{{ radware_provider[0] }}"
    #     state: "{{ state }}"
    #     parameters:
    #       index: 2
    #       state: enabled
    #       ip4_address: 192.168.2.2
    #       peer_ip: 192.168.2.2
    #       ip4_subnet: 255.255.255.0
    #       ip_ver: ipv4
    #       vlan: 2
    
    - name: backup alteon interface 1 config
      radware.radware_modules.alteon_config_l3_interface:
        provider: "{{ radware_provider[1] }}"
        state: "{{ state }}"
        parameters:
          index: 1
          state: enabled
          ip4_address: "{{ ha.peer_interface_va_2 }}"
          peer_ip: "{{ ha.peer_interface_va_1 }}"
          ip4_subnet: 255.255.255.0
          ip_ver: ipv4
          vlan: 1
          
    # - name: backup alteon interface 2 config
    #   radware.radware_modules.alteon_config_l3_interface:
    #     provider: "{{ radware_provider[1] }}"
    #     state: "{{ state }}"
    #     parameters:
    #       index: 2
    #       state: enabled
    #       ip4_address: 192.168.2.3
    #       peer_ip: 192.168.2.2
    #       ip4_subnet: 255.255.255.0
    #       ip_ver: ipv4
    #       vlan: 2

    - name: configure active ha
      radware.radware_modules.alteon_config_high_availability:
        provider: "{{ radware_provider[0] }}"
        state: "{{ state }}"
        parameters:
          mode: switch
          fail_back_mode: always
          preferred_state: active
          advertising_interfaces:
          - 1
          tracked_interfaces:
          - 1
          
    - name: configure standby ha
      radware.radware_modules.alteon_config_high_availability:
        provider: "{{ radware_provider[1] }}"
        state: "{{ state }}"
        parameters:
          mode: switch
          fail_back_mode: always
          preferred_state: standby
          advertising_interfaces:
          - 1
          tracked_interfaces:
          - 1

    - name: active config sync command
      radware.radware_modules.alteon_config_ha_config_sync:
        provider: "{{ radware_provider[0] }}"
        state: "{{ state }}"
        parameters:
          automatic_sync: disabled
          filter_sync: enabled
          ip_interface_sync: enabled
          gateway_sync: enabled
          static_route_sync: enabled
          certificate_sync: enabled
          certificate_passphrase: radware
          peer_authentication_mode: passphrase
          authentication_passphrase: radware
          sync_peers:
            - state: enable
              ip_ver: ipv4
              ip4_address: "{{ ha.peer_interface_va_2 }}"

    - name: backup config sync command
      radware.radware_modules.alteon_config_ha_config_sync:
        provider: "{{ radware_provider[1] }}"
        state: "{{ state }}"
        parameters:
          automatic_sync: enabled
          filter_sync: enabled
          ip_interface_sync: enabled
          gateway_sync: enabled
          static_route_sync: enabled
          certificate_sync: enabled
          certificate_passphrase: radware
          peer_authentication_mode: passphrase
          authentication_passphrase: radware
          sync_peers:
            - state: enable
              ip_ver: ipv4
              ip4_address: "{{ ha.peer_interface_va_1 }}"

    - name: apply configuration
      radware.radware_modules.alteon_mng_config:
        provider: "{{ item }}"
        command: apply
      loop: "{{ radware_provider }}"

